version: "3"
services:
  crdb:
   image: cockroachdb/cockroach:v23.1.1
   ports:
     - "26257:26257"
     - "8080:8080"
   command: start-single-node --insecure
   environment:
    COCKROACH_DATABASE: brev
